### ISSUE TITLE
_responsive incorrect .layout-main width

### ISSUE THREAD

**Issue by BostjanPisler** [primefaces/sakai-ng#13]
_responsive.scss
```scss
@media screen and (min-width: 1729px) {
    .layout-main {
        width: 1478px;
        margin: 0 auto;
    }
}
```

This line causes the layout-main to overlap the left menu
